# https://docs.docker.com/build/ci/github-actions/multi-platform/

name: docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"
      - run: |
          cd MonacoRoslynCompletionProvider/Sample
          dotnet publish -c Release -o ./out

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: |
          cd MonacoRoslynCompletionProvider/Sample/wwwroot
          npm install
          cp -r node_modules ../out/wwwroot

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$calculatedSha" >> "$GITHUB_OUTPUT"

      - name: Deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_DISPATCH }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'poc-aaa',
              repo: 'devops',
              workflow_id: 'playground-deploy.yaml',
              ref: 'main',
              inputs: {
                env: 'development',
                appName: 'monaco-csharp-demo',
                commit_sha: 'sha-${{ steps.vars.outputs.short_sha }}',
              }
            })